version: '2'

services:
  nginx:
    image: aboldyrev/nginx:1.13
    container_name: nginx
    ports:
      - ${NGINX_PORT_HTTP}:80
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./logs/:/var/log/nginx
